name: Test Even Minutes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-even-minute:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test for Even Minute
        run: |
          TEST_RESULT="even"  # Assigning the test result to 'even'
          
          echo "Expected Result: $TEST_RESULT"
          
          if [ "$TEST_RESULT" != "even" ]; then
            echo "Test Failed: Expected 'even', but got '$TEST_RESULT'."
            exit 1
          fi
          echo "Test Passed: The output is even."
