name: Test Even Minutes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-even-minute:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test Even Minute
        run: |
          mvn test -Dtest=EvenMinuteTest
